
CREATE TABLE DEPARTAMENTS(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY 
        (START WITH 1, INCREMENT BY 1) 
        CONSTRAINT departaments_pk PRIMARY KEY,
    nom VARCHAR(256)
);

Create TABLE TREBALLADORS(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY 
        (START WITH 1, INCREMENT BY 1) 
        CONSTRAINT treballadors_pk PRIMARY KEY,
    nom VARCHAR(256),
    title VARCHAR(256),
    --department VARCHAR(256),
    salary DOUBLE,
    salaryAfterTaxes DOUBLE,
    dep_id INTEGER NOT NULL,
    CONSTRAINT dep_id_ref FOREIGN KEY(dep_id) REFERENCES DEPARTAMENTS(id)
);


CREATE TABLE PROJECTS(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY 
        (START WITH 1, INCREMENT BY 1) 
        CONSTRAINT projects_pk PRIMARY KEY,
    nom VARCHAR(256)
);

CREATE TABLE TREB_PROJ(
    treb_id INTEGER NOT NULL,
    proj_id INTEGER NOT NULL,
    CONSTRAINT treb_id_ref FOREIGN KEY(treb_id) REFERENCES TREBALLADORS(id),
    CONSTRAINT proj_id_ref FOREIGN KEY(proj_id) REFERENCES PROJECTS(id)
);